#! /bin/bash
set -e

ENV=$1
ENV=${ENV:-development}
PROJECT_ROOT=$(cd `dirname "${BASH_SOURCE}"`/..; pwd -P)

cd $PROJECT_ROOT
bash ./script/install_dependencies $ENV
NODE_ENV=$ENV npm run build

exit 0