#! /bin/bash
set -e

ENV=$1
ENV=${ENV:-development}
PROJECT_ROOT=$(cd `dirname "${BASH_SOURCE}"`/..; pwd -P)

if ! type -p npm &> /dev/null; then
  echo 'npm not installed'
  exit 1
fi

cd $PROJECT_ROOT
echo 'Installation of npm dependencies'

ensure_yarn() {
  local version=$1
  [[ `yarn -V` == $version ]] && return 0
}

if ! ensure_yarn 1.2.1 ; then
  echo yarn@1.2.1 is NOT installed, need root/admin privileges
  echo Installing yarn

  sudo npm install yarn@1.2.1 -g -q --no-spin --no-progress
fi

NODE_ENV=$ENV yarn

exit 0